# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Kafka node 1
  config.vm.define "confluent-kafka01" do |confluent-kafka01|
    confluent-kafka01.vm.box = "centos/7"
    confluent-kafka01.vm.hostname = "confluent-kafka01"
    confluent-kafka01.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 8260"
    confluent-kafka01.vm.network "private_network", ip: "192.168.56.122"
    confluent-kafka01.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
    end
    confluent-kafka01.vm.provision "shell", path: "..\\_provision_scripts\\provision_centos7.sh"
    confluent-kafka01.vm.provision "shell", path: "..\\_provision_scripts\\provision_confluent-kafka.sh"
  end

  # Kafka node 2
  config.vm.define "confluent-kafka02" do |confluent-kafka02|
    confluent-kafka02.vm.box = "centos/7"
    confluent-kafka02.vm.hostname = "confluent-kafka02"
    confluent-kafka02.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 8260"
    confluent-kafka02.vm.network "private_network", ip: "192.168.56.123"
    confluent-kafka02.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
    end
    confluent-kafka02.vm.provision "shell", path: "..\\_provision_scripts\\provision_centos7.sh"
    confluent-kafka02.vm.provision "shell", path: "..\\_provision_scripts\\provision_confluent-kafka.sh"
  end

  # Kafka node 3
  config.vm.define "confluent-kafka03" do |confluent-kafka03|
    confluent-kafka03.vm.box = "centos/7"
    confluent-kafka03.vm.hostname = "confluent-kafka03"
    confluent-kafka03.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 8260"
    confluent-kafka03.vm.network "private_network", ip: "192.168.56.124"
    confluent-kafka03.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
    end
    confluent-kafka03.vm.provision "shell", path: "..\\_provision_scripts\\provision_centos7.sh"
    confluent-kafka03.vm.provision "shell", path: "..\\_provision_scripts\\provision_confluent-kafka.sh"
  end
end
