# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "elkstackclient"
  config.vm.network "public_network"
  config.vm.network "private_network", ip: "192.168.56.111"
  config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 1
  end
  # config.vm.provision "shell", path: "provision.sh"
end
