# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "saltmasterdlai01.localdomain.com"
  config.vm.network "public_network"
  config.vm.network "private_network", ip: "192.168.56.113"
  config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
  end
  config.vm.provision "shell", path: "provision.sh"

  # Custom mapping for pillar / state files
  #
  # This is not working
  #  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder  "salt-pillar/", "/srv/pillar",
    type: "rsync",
    rsync__exclude: ".git/",
    rsync__auto: true
  config.vm.synced_folder  "salt-state/", "/srv/salt",
    type: "rsync",
    rsync__exclude: ".git/",
    rsync__auto: true
end
