# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "saltmaster01" do |saltmaster01|
    saltmaster01.vm.box = "centos/7"
    saltmaster01.vm.hostname = "saltmaster01.localdomain.com"
    saltmaster01.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 8260"
    saltmaster01.vm.network "private_network", ip: "192.168.56.113"
    saltmaster01.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
    end
    saltmaster01.vm.provision "shell", path: "..\\_provision_scripts\\provision_centos7.sh"
    saltmaster01.vm.provision "shell", path: "..\\_provision_scripts\\provision_saltmaster.sh"

    # Custom mapping for pillar / state files
    #
    # This is not working
    #  saltmaster01.vm.synced_folder '.', '/vagrant', disabled: true
    saltmaster01.vm.synced_folder  "salt-pillar/", "/srv/pillar",
      type: "rsync",
      rsync__exclude: ".git/",
      rsync__auto: true
    saltmaster01.vm.synced_folder  "salt-state/", "/srv/salt",
      type: "rsync",
      rsync__exclude: ".git/",
      rsync__auto: true
  end

  config.vm.define "saltmaster02", autostart: false do |saltmaster02|
    saltmaster02.vm.box = "centos/7"
    saltmaster02.vm.hostname = "saltmaster02.localdomain.com"
    saltmaster02.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 8260"
    saltmaster02.vm.network "private_network", ip: "192.168.56.125"
    saltmaster02.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
    end
    saltmaster02.vm.provision "shell", path: "..\\_provision_scripts\\provision_centos7.sh"
    saltmaster02.vm.provision "shell", path: "..\\_provision_scripts\\provision_saltmaster.sh"

    # Custom mapping for pillar / state files
    #
    # This is not working
    #  saltmaster02.vm.synced_folder '.', '/vagrant', disabled: true
    saltmaster02.vm.synced_folder  "salt-pillar/", "/srv/pillar",
      type: "rsync",
      rsync__exclude: ".git/",
      rsync__auto: true
    saltmaster02.vm.synced_folder  "salt-state/", "/srv/salt",
      type: "rsync",
      rsync__exclude: ".git/",
      rsync__auto: true
  end

end
