# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "saltclientdlai02.localdomain.com"
  config.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 8260"
  config.vm.network "private_network", ip: "192.168.56.115"
  config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
  end
  config.vm.provision "shell", path: "provision.sh"
end
