# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "influxgraf", primary: true do |influxgraf|
      influxgraf.vm.box = "centos/7"
      influxgraf.vm.hostname = "influxgraf"
      influxgraf.vm.network "public_network", bridge: "en0: Wi-Fi (Wireless)"
      influxgraf.vm.network "private_network", ip: "192.168.56.144"
      influxgraf.vm.provider "virtualbox" do |v|
          v.memory = 4096
          v.cpus = 2
      end
      influxgraf.vm.provision "shell", path: "../_provision_scripts/provision_centos7.sh"
      influxgraf.vm.provision "shell", path: "../_provision_scripts/provision_influx_grafana.sh"
    end
  end
