# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "k8smaster", primary: true do |k8smaster|
    k8smaster.vm.box = "centos/7"
    k8smaster.vm.hostname = "k8smaster"
    k8smaster.vm.network "public_network", bridge: "en0: Wi-Fi (Wireless)"
    k8smaster.vm.network "private_network", ip: "192.168.56.141"
    k8smaster.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
    end
    k8smaster.vm.provision "shell", path: "../_provision_scripts/provision_centos7.sh"
  end

  config.vm.define "node01", autostart: true do |node01|
    node01.vm.box = "centos/7"
    node01.vm.hostname = "node01"
    node01.vm.network "public_network", bridge: "en0: Wi-Fi (Wireless)"
    node01.vm.network "private_network", ip: "192.168.56.142"
    node01.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
    end
    node01.vm.provision "shell", path: "../_provision_scripts/provision_centos7.sh"
  end

  config.vm.define "node02", autostart: true do |node02|
    node02.vm.box = "centos/7"
    node02.vm.hostname = "node02"
    node02.vm.network "public_network", bridge: "en0: Wi-Fi (Wireless)"
    node02.vm.network "private_network", ip: "192.168.56.143"
    node02.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
    end
    node02.vm.provision "shell", path: "../_provision_scripts/provision_centos7.sh"
  end
end
