# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/6"
  config.vm.hostname = "centos6clean"
  config.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 8260"
  config.vm.network "private_network", ip: "192.168.56.118"
  config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
  end
end
