---
- name: Ensure that Apache is installed
  yum:
    name=httpd
    state=present
  when:
    ansible_os_family == "RedHat"

- name: Start Apache Service
  service:
    name=httpd
    enabled=yes
    state=started

# Creating test files
# The issue with touch is, it will always cause a -change-
#
# - name: Placing (touch) a test file
#   file:
#     path=/tmp/{{ item }}
#     state=touch
#     owner=root
#     mode=0777
#   with_items:
#     - test
#     - test1
#     - test2

# Creating test files
- name: Placing a line in the test file.
  lineinfile:
    dest=/tmp/test
    line="This is a line i am enforcing"
    state=present
    insertafter=EOF

# Creating test files
- name: Placing a test file via template
  template:
    src=test.j2
    dest=/tmp/test.j2
  notify:
    - Restart Apache

# This is a way to get debugging info
- name: Debugging message
  debug:
    msg=This is a debug message {{ item }}
  with_items:
    - "{{ yourname }}"
    - "{{ quest }}"
    - "{{ favcolor }}"
