# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "mssqlserver", primary: true do |mssqlserver|
    mssqlserver.vm.box = "centos/7"
    mssqlserver.vm.hostname = "mssqlserver"
    mssqlserver.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 8260"
    mssqlserver.vm.network "private_network", ip: "192.168.56.130"
    mssqlserver.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
    end
    mssqlserver.vm.provision "shell", path: "..\\_provision_scripts\\provision_centos7.sh"
    mssqlserver.vm.provision "shell", path: "..\\_provision_scripts\\provision_mssqlserver.sh"
  end
end
