# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "elkstackbox"
  config.vm.network "public_network"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
  end
  config.vm.provision "shell", path: "provision.sh"
end
