---
- hosts: webserver01  # You can use groups, or Regex match here:
  become: true
  become_user: root
  roles:
    - webserver

- hosts: dbserver01
  become: true
  become_user: root
  roles:
    - dbserver

- hosts: win2k12db01
  roles:
    - windows


# You can import other playbooks like this:
# - import_playbook: webserver.yml

