# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "centos7clean01", primary: true do |centos7clean01|
    centos7clean01.vm.box = "centos/7"
    centos7clean01.vm.hostname = "centos7clean01"
    centos7clean01.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 8260"
    centos7clean01.vm.network "private_network", ip: "192.168.56.112"
    centos7clean01.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
    end
    centos7clean01.vm.provision "shell", path: "../_provision_scripts/provision_centos7.sh"
  end

  config.vm.define "centos7clean02", autostart: true do |centos7clean02|
    centos7clean02.vm.box = "centos/7"
    centos7clean02.vm.hostname = "centos7clean02"
    centos7clean02.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 8260"
    centos7clean02.vm.network "private_network", ip: "192.168.56.121"
    centos7clean02.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
    end
    centos7clean02.vm.provision "shell", path: "../_provision_scripts/provision_centos7.sh"
  end

  config.vm.define "centos7clean03", autostart: true do |centos7clean03|
    centos7clean03.vm.box = "centos/7"
    centos7clean03.vm.hostname = "centos7clean03"
    centos7clean03.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 8260"
    centos7clean03.vm.network "private_network", ip: "192.168.56.140"
    centos7clean03.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
    end
    centos7clean03.vm.provision "shell", path: "../_provision_scripts/provision_centos7.sh"
  end
end
