# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "redis01", primary: true do |redis01|
    redis01.vm.box = "centos/7"
    redis01.vm.hostname = "redis01"
    redis01.vm.network "public_network", bridge: "en0: Wi-Fi (Wireless)"
    redis01.vm.network "private_network", ip: "192.168.56.145"
    redis01.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
    end
    redis01.vm.provision "shell", path: "../_provision_scripts/provision_centos7.sh"
    redis01.vm.provision "shell", path: "../_provision_scripts/provision_redis.sh"
  end
end
